### ISSUE TITLE
How to Add Multiple Card Brand Names ? i.e. VISA ,MASTER?

### ISSUE THREAD

**Issue by immi420** [ahmedelkhyary/hyperpay#14]
like its shown in HyperPay Prebuilt UI?

https://hyperpay.docs.oppwa.com/tutorials/mobile-sdk/prebuilt-ui

Love this Library , Awesome work Brother <3

**Comment by ahmedelkhyary** [comment]
Hi bro 
Please check last version released today 1.0.9 

![](https://user-images.githubusercontent.com/70061912/232218028-66378ef3-19c3-4af1-8d61-890377d24828.jpg )
