### ISSUE TITLE
Application Crashed

### ISSUE THREAD

**Issue by MVP-APP-1234** [ahmedelkhyary/hyperpay#18]
When I tried to pass the Checkout ID to "flutterHyperPay.readyUICards" my app crashed.

I get the Checkout ID from (Note: I got this URL from hyperPay official site -> https://wordpresshyperpay.docs.oppwa.com/tutorials/server-to-server/tokenisation): 
    final url = Uri.parse('https://eu-test.oppwa.com/v1/checkouts');
    final response = await http.post(url2, body: {
      "amount": "92.00",
      "currency": "USD",
      "paymentType": "DB",
      "entityId": "8a8294174b7ecb28014b9699220015ca",
    }, headers: {
      "Authorization":
          "Bearer OGE4Mjk0MTc0YjdlY2IyODAxNGI5Njk5MjIwMDE1Y2N8c3k2S0pzVDg="
    });

Warning Error I get from Flutter:
Restarted application in 1,336ms.
I/flutter ( 5703): asdasd: C8F4E334CD3CFD3A1AF2BAF2C1457D24.uat01-vm-tx01  &&&  27ACAA3AD5EAA2CBBA1E2FF2FB0ACE46.uat01-vm-tx01
I/flutter ( 5703): asdasd: 46  &&&  46
W/DynamiteModule( 5703): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 5703): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 5703): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
2
E/RecyclerView( 5703): No adapter attached; skipping layout
I/AssistStructure( 5703): Flattened final assist data: 6204 bytes, containing 2 windows, 48 views
D/OpenGLRenderer( 5703): endAllActiveAnimators on 0xecf2ee70 (RippleDrawable) with handle 0xb82d2d50
2
W/System  ( 5703): A resource failed to call end.
I/chatty  ( 5703): uid=10154(com.example.hyperpay_plugin_tutorial) FinalizerDaemon identical 1 line
W/System  ( 5703): A resource failed to call end.
E/AndroidRuntime( 5703): FATAL EXCEPTION: Thread-73
E/AndroidRuntime( 5703): Process: com.example.hyperpay_plugin_tutorial, PID: 5703
E/AndroidRuntime( 5703): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/Gson;
E/AndroidRuntime( 5703): 	at com.oppwa.mobile.connect.provider.c.b(OppTransactionResponseParser.java:7)
E/AndroidRuntime( 5703): 	at com.oppwa.mobile.connect.provider.c.a(OppTransactionResponseParser.java:2)
E/AndroidRuntime( 5703): 	at com.oppwa.mobile.connect.provider.b.a(OppRequestHelper.java:31)
E/AndroidRuntime( 5703): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.d(OppPaymentProvider.java:32)
E/AndroidRuntime( 5703): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.b(OppPaymentProvider.java:35)
E/AndroidRuntime( 5703): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.a(OppPaymentProvider.java:122)
E/AndroidRuntime( 5703): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.$r8$lambda$8lIPs3YCgwV4TA8Itn9v9pgwsx8(Unknown Source:0)
E/AndroidRuntime( 5703): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider$$ExternalSyntheticLambda0.run(Unknown Source:8)
E/AndroidRuntime( 5703): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 5703): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.Gson" on path: DexPathList[[zip file "/data/app/~~ZawXOUsXx9sDQdVPH3wymw==/com.example.hyperpay_plugin_tutorial-DzkPsQhTnDleayOeIzalLw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ZawXOUsXx9sDQdVPH3wymw==/com.example.hyperpay_plugin_tutorial-DzkPsQhTnDleayOeIzalLw==/lib/x86, /data/app/~~ZawXOUsXx9sDQdVPH3wymw==/com.example.hyperpay_plugin_tutorial-DzkPsQhTnDleayOeIzalLw==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime( 5703): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 5703): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 5703): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 5703): 	... 9 more
I/Process ( 5703): Sending signal. PID: 5703 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by Amryasin** [comment]
I recommend you to  not use this way to get checkout to get a test checkout you can use this code  can you please check and tell me this crash may be hapend if checkout not valid

if you try to use the enitity id  from the documention it not working because i think it's just data for demo porops 

you can try this code to get a test check out this code from the example in package 
[https://github.com/ahmedelkhyary/hyperpay/blob/78c21d84f96c7457d5bd335d363ca5bdfe7599c8/example/lib/main.dart#L99](url)
` Future<String?> getCheckOut() async {
    final url = Uri.parse('https://dev.hyperpay.com/hyperpay-demo/getcheckoutid.php');
    final response = await http.get(url);
    if (response.statusCode == 200) {
      dev.log(json.decode(response.body)['id'].toString(), name: "checkoutId");
      return json.decode(response.body)['id'];
    }else{
      dev.log(response.body.toString(), name: "STATUS CODE ERROR");
      return null;
    }
  }`

**Comment by ahmedelkhyary** [comment]
@MVP-APP-1234 
use below Link to get test checkoutId 
https://dev.hyperpay.com/hyperpay-demo/getcheckoutid.php
