### ISSUE TITLE
Custom ui: month need to be two digits and it is int

### ISSUE THREAD

**Issue by YazanAlaynin2** [ahmedelkhyary/hyperpay#20]
the problem is that i need to pass the month as int but when i pass month like from 1 to 9 it say expiry month is not valid.  
this need to be fixes by changing the month to string maybe and get it like this (05) or you solve it from the package it self and add the zero for numbers from 1 to 9.

**Comment by ahmedelkhyary** [comment]
I hope u are doing well
We will work on it in the next version to accept all solutions formats

**Comment by YazanAlaynin2** [comment]
@ahmedelkhyary when it will be released?
