### ISSUE TITLE
Amount and currency field pass

### ISSUE THREAD

**Issue by sabikrahat** [ahmedelkhyary/hyperpay#23]
Hello! How can I pass amount and currency parameter ?

**Comment by ahmedelkhyary** [comment]
Hi sabikrahat , 
You can't pass amount because of checkoutId already have amount , you need only pass checkoutId

**Comment by ahmedelkhyary** [comment]
@sabikrahat

**Comment by sabikrahat** [comment]
yeah.... I have solved the issue......... however I think you should mention it in readme.md file and also you should create a function to get the actual status of the payment integration. I have done all these stubs in my project.. If you want I can make a PR request.

**Comment by ahmedelkhyary** [comment]
ok bro u can make PR

**Comment by sabikrahat** [comment]
@ahmedelkhyary I have made a PR..... Please check it out... Thank you..... Sorry for the delay.
