### ISSUE TITLE
iOS build/archive issue

### ISSUE THREAD

**Issue by MoeAl-Ani** [ahmedelkhyary/hyperpay#24]
Hi,

I hope you are doing well,

I m facing an issue when building to iOS, 

ERROR: "iphoneos/hyperpay_plugin/hyperpay_plugin.modulemap' not found"

do you happen to know what could be the root cause?

Br,

**Comment by ahmedelkhyary** [comment]
Hi MoeAi-Ani 
Can you try again because I have not seen this problem before 

and is code work well before archive

**Comment by MoeAl-Ani** [comment]
Hi, 

it fixed, actually it was my bad with wrong xcode build config.

Sorry for the inconvenience.

**Comment by ahmedelkhyary** [comment]
it's ok bro , u are welcome
