### ISSUE TITLE
Checkout Result Error

### ISSUE THREAD

**Issue by shirazhussain123** [ahmedelkhyary/hyperpay#28]
Hi,

I'm getting an error PaymentResult.error - Checkout Result Error. This when I enter the card details and click on Pay now in readyUI. It's not going to the OTP screen.

The thing is, when I test in debug mode it's working but when I test in release mode, it gives the above error.

What can be the problem.

**Comment by ahmedelkhyary** [comment]
@shirazhussain123  

Hey bro 

sorry for reply late , r u still get this error
