### ISSUE TITLE
Pod Install Issue

### ISSUE THREAD

**Issue by arsallion313786** [ahmedelkhyary/hyperpay#31]
when i write this piece of code for pod install for iOS

pod 'hyperpay_sdk', :git => 'https://github.com/ahmedelkhyary/hyperpay_sdk.git'
$static_framework = ['hyperpay_plugin']
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
end

got this error
[!] CocoaPods could not find compatible versions for pod "hyperpay_sdk":
  In Podfile:
    hyperpay_plugin (from `.symlinks/plugins/hyperpay_plugin/ios`) was resolved to 0.0.2, which depends on
      hyperpay_sdk (~> 4.12.0)

    hyperpay_sdk (from `https://github.com/ahmedelkhyary/hyperpay_sdk.git`)

**Comment by ahmedelkhyary** [comment]
@arsallion313786  

Hi bro 

Make sure u use last version 2.0.4 and try to delete lock file and make pod install again

**Comment by arsallion313786** [comment]
@ahmedelkhyary bro
In flutter i am added plugin as 
hyperpay_plugin:
and for iOS i have added first time
