### ISSUE TITLE
Not able to open the app in release mode

### ISSUE THREAD

**Issue by nimesh-devloper** [ahmedelkhyary/hyperpay#34]
Hello

I have integrated hyper pay plugin in my app and after that I am not able to open my app in release mode. 

I think the issue is coming because of the    `<intent-filter>`

```
<action android:name="android.intent.action.VIEW" />
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.LAUNCHER" />
                <data android:scheme="com.saan.sa.payment" />
```
                
                
When I remove this it will work properly but when I add this in my manifest file my app completes the installation but not opening in release mode. 

please guide me.

**Comment by ahmedelkhyary** [comment]
Hello @nimesh-devloper  

This code you are mention in above used when making a payment outside the app (Like open browser) and back into the app

Can you give me more details about your issue or message appear 

Thanks

**Comment by nimesh-devloper** [comment]
Hello @ahmedelkhyary 

I have found this code from your plugin Redmi section. 

![Screenshot of hyperpay_plugin _ Flutter Package](https://github.com/ahmedelkhyary/hyperpay/assets/138967913/5b761a31-26b0-48a1-a40b-5634c33ed140)


when I added this code after that I was not able to open my app in the release mode. 

To test I removed this code from my Menyfest file and then I was able to open my app in release mode but the problem is after that I cannot pay with the hyper_pay plugin. 

Please guide me. 

Do I have to remove all this code from the intent filter?

`                <action android:name="android.intent.action.VIEW" />
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.LAUNCHER" />
                <data android:scheme="com.saan.sa.payment" />`

**Comment by nimesh-devloper** [comment]
when i have removed this code i am stuck at this screen. 
![Screenshot_20231218-101707_Samsung Internet](https://github.com/ahmedelkhyary/hyperpay/assets/138967913/09f34d4d-32f9-48b4-964a-4b8801cb42f3)

**Comment by ahmedelkhyary** [comment]
> Hello @ahmedelkhyary
> 
> I have found this code from your plugin Redmi section.
> 
> ![Screenshot of hyperpay_plugin _ Flutter Package](https://private-user-images.githubusercontent.com/138967913/291148386-5b761a31-26b0-48a1-a40b-5634c33ed140.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODY1NDUsIm5iZiI6MTcwMjg4NjI0NSwicGF0aCI6Ii8xMzg5Njc5MTMvMjkxMTQ4Mzg2LTViNzYxYTMxLTI2YjAtNDhhMS1hNDBiLTU2MzRjMzNlZDE0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNzU3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzk4MTA2NmFhNTk0MGI3ZmU5OTQzZDkyNjUyYjU5NTkzOGM1MjNlYTUwZDVhODg4MGY5ZTY2ZjlmMjYwMTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zC-1ucgdMgeC3NKZ1eJIvaMSP7WHKUXpYJSNN-ziJVQ)
> 
> when I added this code after that I was not able to open my app in the release mode.
> 
> To test I removed this code from my Menyfest file and then I was able to open my app in release mode but the problem is after that I cannot pay with the hyper_pay plugin.
> 
> Please guide me.
> 
> Do I have to remove all this code from the intent filter?
> 
> ` <action android:name="android.intent.action.VIEW" /> <action android:name="android.intent.action.MAIN" /> <category android:name="android.intent.category.BROWSABLE" /> <category android:name="android.intent.category.DEFAULT" /> <category android:name="android.intent.category.LAUNCHER" /> <data android:scheme="com.saan.sa.payment" />`

It is not necessary for you to remove this code as it is required to back again into the application after payment. 

Give me more details about the error message or video record

**Comment by nimesh-devloper** [comment]
I am not getting any error when I add this intent code. but when I create a release apk with this code I am not able to open this app. 

![Screenshot_20231218-141838_Package installer](https://github.com/ahmedelkhyary/hyperpay/assets/138967913/b2ac7781-1547-45e2-9a2b-211513be535b)

the release app is not visible in my app drawer in my real device. 

I am sharing my manifest file code please check this is it okay ?

`  
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.iqonic.servicebooking">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />

    <application
        android:icon="@mipmap/ic_launcher"
        android:label="Saan"
        android:requestLegacyExternalStorage="true"
        tools:replace="android:label">
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <meta-data
                android:name="com.google.firebase.messaging.default_notification_icon"
                android:resource="@drawable/ic_stat_onesignal_default" />

            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.LAUNCHER" />
                <data android:scheme="com.saan.sa.payment" />
            </intent-filter>
        </activity>
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="AIzaSyCHJwjZsjGSOBc18-3mJM8tddssCqDYoV9tQ" />
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <service
            android:name="MyNavigationService"
            android:foregroundServiceType="location" >
    </service>
    </application>
</manifest>

`

**Comment by ahmedelkhyary** [comment]
please add me on your repository project to check  @nimesh-devloper 
mcli3064@gmail.com

**Comment by ahmedelkhyary** [comment]
discord link https://discord.com/invite/T8TyGxpGBS

**Comment by nimesh-devloper** [comment]
No, I can't add you to my repo. 
Can you please share any other Test Project integrated with Hyperpay_plugin (flutter)?

So I can Compare it with my Project.

**Comment by ahmedelkhyary** [comment]
https://github.com/ahmedelkhyary/hyperpay/tree/main/example

**Comment by nimesh-devloper** [comment]
Thank you for the help.

This work for my code

initially I have only added 

` 
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />

                <category android:name="android.intent.category.LAUNCHER" />
                <data android:scheme="com.testpayment.payment" />
            </intent-filter>
            `
            
  Then I updated this in my Manyfest file.
  
  `<intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />

                <category android:name="android.intent.category.LAUNCHER" />
                <data android:scheme="com.testpayment.payment" />
            </intent-filter>`
