### ISSUE TITLE
Why the custom UI not responding ?

### ISSUE THREAD

**Issue by SreelekhN** [ahmedelkhyary/hyperpay#35]
on adding custom ui and calling it, nothing really happens.
just getting a success immidiately.

And for ready ui, mada, visa and mastercard need their own separate checkout id going live.
U cant pass a single checkout id for all actions, atleast thats the status i got from backend team.
Is theres any work around for it, if not this ready ui is kinda useless now

**Comment by ahmedelkhyary** [comment]
Test ?

**Comment by ahmedelkhyary** [comment]
@SreelekhN
