### ISSUE TITLE
Track the callback via status code instead of String value

### ISSUE THREAD

**Issue by shashoug** [ahmedelkhyary/hyperpay#37]
Is there any way to get the response with status code instead of string value to validate each scenario?

**Comment by ahmedelkhyary** [comment]
after get response you should use endpoint to check payment status from backend 
because the response that back from plugin not tell you the transaction is success or failed

**Comment by shashoug** [comment]
@ahmedelkhyary  It will be checked with checkoutId & entityId right?

**Comment by ahmedelkhyary** [comment]
right
