### ISSUE TITLE
Apple Pay

### ISSUE THREAD

**Issue by shashoug** [ahmedelkhyary/hyperpay#38]
I've followed all the documentations regarding Apple Pay setup, All merchant and processing certificates has been generated successfully, In the App, When pressing the Apple Pay button, Then pressing the pay button the Apple Pay sheet closes and no any callback for the payment if its done or failed with no reason, I've tried to trigger the response from the `paymentResult` object and it always returns `paymentResult.error `, So long story short, Apple Pay doesn't seems to work for me. 

Is there any documentation for that issue/integration?

**Comment by ahmedelkhyary** [comment]
https://github.com/ahmedelkhyary/applepay_merchantId_config

**Comment by ahmedelkhyary** [comment]
after download processing and merchant certificate you should send them to hyperpay team to complete verification

**Comment by shashoug** [comment]
As mentioned, I've followed all the steps. 
I got something hopefully it does something with my situation, 
I've tried to log `paymentResultData.errorString` it's return with error : Error: Optional(<OPPTransaction: 0x600002187390>).

I searched with this code error but nothing to be found in your status code example in the website.

**Comment by Elkassas-dev** [comment]
@shashoug 
i have the same error did you solve it ?

**Comment by janithsg** [comment]
@shashoug @ahmedelkhyary I have the same issue. 
MerchantID config and other things all correct.
It gives the ApplePay popup sheet and complete the payment. 
But it always returning `PaymentResult.error`. There is no any error description or anything to identify the error cause.

Have you resolved it? Please share.

**Comment by ahmedelkhyary** [comment]
@janithsg 
Your issue is related to Hyperpay. Please contact their support team.
