### ISSUE TITLE
Adding async payment?

### ISSUE THREAD

**Issue by hewa-jalal** [ahmedelkhyary/hyperpay#4]
Thank you for creating this package, but do you have plans on adding asynchronous payment as well?

**Comment by ahmedelkhyary** [comment]
I hope you are doing well
it's already redirection takes place to allow the account holder to complete/verify (Like OTP) the payment, after this the account holder is redirected back to the app

**Comment by hewa-jalal** [comment]
i am sorry but can you clarify furthermore?

**Comment by ahmedelkhyary** [comment]
**Asynchronous Payments**
In an asynchronous workflow a redirection takes place to allow the account holder to complete/verify the payment. After this the account holder is redirected back to the app and the status of the payment can be queried.

**Android**
Register a custom URL scheme

Define the name of your custom scheme (for example companyname) and add intent filter to your target activity in the AndroidManifest.xml

**iOS**
Register a custom URL scheme
In Xcode, click on your project in the Project Navigator and navigate to App Target > Info > URL Types
Click [+] to add a new URL type
Under URL Schemes, enter your app switch return URL scheme. This scheme must start with your app's Bundle ID. For example, if the app bundle ID is com.companyname.appname, then your URL scheme could be com.companyname.appname.payments.

_please check reference , _Because we are already implementation this part__

https://wordpresshyperpay.docs.oppwa.com/tutorials/mobile-sdk/custom-ui/asynchronous-payments

**Comment by hewa-jalal** [comment]
but how do i get the `intent.scheme` in flutter?

**Comment by ahmedelkhyary** [comment]
sorry , could you please explain what you mean?
if you mean about `intent scheme` is a name that identifies either a unique object or a unique class of objects, where the "object" or class may be an idea, physical countable

**Comment by ahmedelkhyary** [comment]
It already exists inside the plugin

**Comment by hewa-jalal** [comment]
and how do i use it?

**Comment by ahmedelkhyary** [comment]
No need to do these steps again ? plugins do these steps automatically

**Comment by hewa-jalal** [comment]
that's awesome, but this is what i got when i used the plugin from my `gate2play` provider!
![image](https://user-images.githubusercontent.com/52101936/223152161-7d200bc8-5120-4375-8e07-10ff8aeec3a6.png)

**Comment by ahmedelkhyary** [comment]
please check 3Ds reference 
https://wordpresshyperpay.docs.oppwa.com/tutorials/mobile-sdk/emv-3ds#ready-to-use-ui

![image](https://user-images.githubusercontent.com/70061912/223192705-bb940e52-8b2b-4ef7-9d78-a81a7a840ac6.png)

**setup 3Ds in plugin,** 
![image](https://user-images.githubusercontent.com/70061912/223192227-25d7278f-985a-4962-b938-c7fa36583c34.png)

**Comment by ahmedelkhyary** [comment]
Which operating system was used, Android or IOS?

**Comment by hewa-jalal** [comment]
so all i need to do for 3D to work is change the mode to live instead of test?

**Comment by ahmedelkhyary** [comment]
Is it possible to work with you on anydesk to determine what to do?

**Comment by hewa-jalal** [comment]
yes sure i will be thankful, here is my discord if you want to communicate there
hiwa-47#9877
