### ISSUE TITLE
Resource Path

### ISSUE THREAD

**Issue by karimSalahx** [ahmedelkhyary/hyperpay#41]
How can I get the resource path so I can check on the payment status?

**Comment by ahmedelkhyary** [comment]
u need create API to check payment status

**Comment by karimSalahx** [comment]
What endpoint should I use exactly, can you provide more details or a documentation since the package does not clear anything up regarding this matter @ahmedelkhyary

**Comment by ahmedelkhyary** [comment]
3. Get the payment status
https://wordpresshyperpay.docs.oppwa.com/tutorials/integration-guide
