### ISSUE TITLE
using wrong  ipworks3ds_sdk_deploy.xcframework in release mode 

### ISSUE THREAD

**Issue by abdullahalamodi** [ahmedelkhyary/hyperpay#45]
Based on hyperpay documentation 

> There are two versions of the ipworks3ds_sdk.xcframework included: one to be used for development and one for production. The production version includes more strict security measures that would not allow for common development processes to occur, including running with attached debuggers or using simulators/emulators. **The deployment version includes _deploy in the filename.** 

we should use 
`ipworks3ds_sdk_deploy.xcframework ` in deployment mode 
and 
`ipworks3ds_sdk.xcframework` in release mode 

but as I found in android build.gradle that you using ipworks3ds_sdk_deploy.xcframework in release mode !!

code android build.gradle 

```
dependencies {
    implementation(name: "oppwa.mobile-release", ext: 'aar')
    debugImplementation(name: "ipworks3ds_sdk", ext: 'aar')
    releaseImplementation(name: "ipworks3ds_sdk_deploy", ext: 'aar')
    ...
}
```

**Comment by ahmedelkhyary** [comment]
@abdullahalamodi please check 

https://wordpresshyperpay.docs.oppwa.com/integrations/mobile-sdk/emv-3ds-new-flow

![image](https://github.com/ahmedelkhyary/hyperpay/assets/70061912/079b87aa-c9eb-4d47-91ef-e6a3d9f6bec8)

**Comment by abdullahalamodi** [comment]
@ahmedelkhyary  I did, but also look at this on the main page of integration 
https://wordpresshyperpay.docs.oppwa.com/integrations/mobile-sdk/first-integration
<img width="1048" alt="hyperpay dev" src="https://github.com/ahmedelkhyary/hyperpay/assets/39647459/ac601dca-5f64-4cf4-b837-9ee5082873a2">

**Comment by ahmedelkhyary** [comment]
@abdullahalamodi 

The **deployment** version includes _deploy in the filename.

deployment not development

**Comment by abdullahalamodi** [comment]
I see you're right
