### ISSUE TITLE
Asset validation failed: Invalid Executable contains bitcode in Mapbox.framework

### ISSUE THREAD

**Issue by houzifakroom** [ahmedelkhyary/hyperpay#49]
When submitting my iOS app to TestFlight, I receive the following error during the asset validation:

Asset validation failed Invalid Executable. The executable 'Катаурафіко.app/Frameworks/Mapbox.framework/Mapbox' contains bitcode. (ID: aca3990b-17de-4558-ac9-432ff150444f)

I have tried to disable bitcode and strip it in the `Podfile` for the HyperPay SDK, but the issue persists.

**Steps to Reproduce:**
1. Integrate `hyperpay_plugin` (version 0.0.3) with `hyperpay_sdk` (version 5.1.0).
2. Build and archive the iOS app using Xcode 15.
3. Submit the app to TestFlight.
4. Encounter the bitcode-related error during asset validation.

**Additional Details:**
- Xcode Version: 15
- Flutter Version: 3.19.5
- HyperPay Plugin Version: ^2.0.8
- HyperPay SDK Version: 5.1.0
- I have tried to strip bitcode manually from the HyperPay SDK in my `post_install` section of the `Podfile`, but the error remains.

**Possible Solutions:**
- Please provide guidance on ensuring Bitcode is properly stripped from the SDK.

**Comment by ahmedelkhyary** [comment]
Thanks @houzifakroom 

I will check about this problem 

same here 
https://github.com/ahmedelkhyary/hyperpay_sdk/issues/7#issue-2540275904
