### ISSUE TITLE
do not work with android 14

### ISSUE THREAD

**Issue by SaurabhAlmighty** [ahmedelkhyary/hyperpay#50]
![image_2024_09_20T12_30_15_301Z](https://github.com/user-attachments/assets/0c4b1d7b-a9d6-4211-92cd-223e44b1c697)

**Comment by ahmedelkhyary** [comment]
Thanks @SaurabhAlmighty  

I will check

**Comment by SaurabhAlmighty** [comment]
you can check with new android device api level above 13

**Comment by ahmedelkhyary** [comment]
Working fine @SaurabhAlmighty  on android 14 and 15 

![image](https://github.com/user-attachments/assets/6520c44e-bc69-40e5-9c2b-ca4da3e6bb7d)
![image](https://github.com/user-attachments/assets/30647bf4-236e-4a63-aeef-78eeb57d332e)

**Comment by SaurabhAlmighty** [comment]
when can i check?
