### ISSUE TITLE
Live mode

### ISSUE THREAD

**Issue by Mo-Meshrif** [ahmedelkhyary/hyperpay#6]
Thank you for your effort to make this excellent library. I tried it and it works without problems or complications in the test mode, but I encountered some issues when converting to the live mode, which is as follows:
1-when entering the checkout id which I get it from live prepare checkout Api, the payment form doesn't create.
2-Although I have selected live mode when entering the checkout id which I get it from test prepare checkout API, the payment form created.
In the end, I realized that the library works in test mode, even if I select live mode. I think it may be because "com.testpayment.payment" or another reason causes those issues.

**Comment by ahmedelkhyary** [comment]
I hope you are doing well 
can you give me some details
which platform you are trying , and some of the checkoutId's that try of them on Live mode

**Comment by Mo-Meshrif** [comment]
I tried it on ios and android .The checkoutId which generated from live prepare checkout worked without any issues in the web integration but not worked flutter integration.

**Comment by AhmedAElllatif** [comment]
give me some of the checkoutId's that try on Live mode

**Comment by ahmedelkhyary** [comment]
give me some of the checkoutId's that try on Live mode

**Comment by Mo-Meshrif** [comment]
Here you are . 
A36910979DFE1E019875CF09B01DF1AC.prod01-vm-tx02

**Comment by ahmedelkhyary** [comment]
invalid checkoutId 
![image](https://user-images.githubusercontent.com/70061912/229307102-99ea77f0-825f-4dfb-a6fa-f5857c442aad.png)

try with with this script
```
<script src="https://eu-prod.oppwa.com/v1/paymentWidgets.js?checkoutId=A36910979DFE1E019875CF09B01DF1AC.prod01-vm-tx02"></script>
<form
  action="{shopperResultUrl}"
  class="paymentWidgets"
  data-brands="VISA MASTER AMEX"
></form>

```

**Comment by Mo-Meshrif** [comment]
I need any way to contact you like facebook or whatsapp

**Comment by ahmedelkhyary** [comment]
01204561050
