### ISSUE TITLE
Android App Crash Issue 

### ISSUE THREAD

**Issue by GithubUser18974** [ahmedelkhyary/hyperpay#60]
![Screenshot 2024-12-28 232159](https://github.com/user-attachments/assets/8f6266e1-cd82-4c15-a920-0d1cca288683)
FATAL EXCEPTION: main
E/AndroidRuntime(12511): Process: com.mdsoft.payment, PID: 12511
E/AndroidRuntime(12511): java.lang.SecurityException: Settings key: <enabled_input_methods> is only readable to apps with targetSdkVersion lower than or equal to: 33
E/AndroidRuntime(12511): 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3532)
E/AndroidRuntime(12511): 	at android.provider.Settings$Secure.getStringForUser(Settings.java:6951)
E/AndroidRuntime(12511): 	at android.provider.Settings$Secure.getString(Settings.java:6917)
E/AndroidRuntime(12511): 	at nts.ഉ.ዎ(Unknown Source:4)
E/AndroidRuntime(12511): 	at nts.ഉ.ᦝ(Unknown Source:2637)
E/AndroidRuntime(12511): 	at nts.ѹ.initialize(Unknown Source:200)
E/AndroidRuntime(12511): 	at z3.b.j(Unknown Source:32)
E/AndroidRuntime(12511): 	at z3.b.s(Unknown Source:18)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.provider.p.d0(Unknown Source:12)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.f.r(Unknown Source:14)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.f.v(Unknown Source:18)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.f.B(Unknown Source:56)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.f.N(Unknown Source:15)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.f.l(Unknown Source:0)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.c.a(Unknown Source:2)
E/AndroidRuntime(12511): 	at androidx.fragment.app.h0$o.a(Unknown Source:2)
E/AndroidRuntime(12511): 	at androidx.fragment.app.h0.x1(Unknown Source:18)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.u1.W1(Unknown Source:27)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.u1.Q1(Unknown Source:0)
E/AndroidRuntime(12511): 	at com.oppwa.mobile.connect.checkout.dialog.t1.onClick(Unknown Source:2)
E/AndroidRuntime(12511): 	at android.view.View.performClick(View.java:8028)
E/AndroidRuntime(12511): 	at android.view.View.performClickInternal(View.java:8005)
E/AndroidRuntime(12511): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
E/AndroidRuntime(12511): 	at android.view.View$PerformClick.run(View.java:31229)
E/AndroidRuntime(12511): 	at android.os.Handler.handleCallback(Handler.java:959)
E/AndroidRuntime(12511): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(12511): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(12511): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(12511): 	at android.app.ActivityThread.main(ActivityThread.java:8705)
E/AndroidRuntime(12511): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12511): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime(12511): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
***************************************************************************************************************************
DESCRIPTION
application crashes on payment success 
flutter SDK:  3.24.1
        classpath 'com.android.tools.build:gradle:7.2.0'

**Comment by ahmedelkhyary** [comment]
duplicate

**Comment by GithubUser18974** [comment]
@ahmedelkhyary  where is can find the duplication for it  ? and did you solved it ?

**Comment by ahmedelkhyary** [comment]
#56
