### ISSUE TITLE
can you make the payment type customized that i can choose between "PA" and "DB" 

### ISSUE THREAD

**Issue by yousefnjadat** [ahmedelkhyary/hyperpay#7]

**Comment by Amryasin** [comment]
At the moment we depend on the checkout come from backend.
You can request it from your backend unitll we finsh it and we are planing to add in next releases with this options.

**Comment by Amryasin** [comment]
You can ask your back end to handel this pakcage depend on the checkout come from your backend
 
![image](https://user-images.githubusercontent.com/61648679/229753812-ad653dce-e124-4e00-91d9-9383e31b41f5.png)
